apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
  namespace: shwe1
spec:
  #revisionHistoryLimit: 10
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:                                     #---- NODE SELECTOR-------
      #1 nodeSelector:
      #   name: node-zerO

      # affinity:                             #--- NODE AFFINITY/ANTI AFFINITY (HARD RULE)--------
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:    #hard-rule (mandatory to satisfy)
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: name
      #           operator: In                                 # In / NotIn
      #           values:
      #           - node-zero
      
      # affinity:                             #--- NODE AFFINITY/ANTI AFFINITY (SOFT RULE)-----------
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:  #preffered - assigns to some node if it doesnt match node lables also
      #     - weight: 1
      #       preference:
      #         matchExpressions:
      #         - key: name
      #           operator: In
      #           values:
      #           - node-zer0
      #     - weight: 30          # as weight to this is high this is prioratized---------
      #       preference:
      #         matchExpressions:
      #         - key: name
      #           operator: In
      #           values:
      #           - node-zero      

      # affinity:                             #--- POD AFFINITY/ANTI AFFINITY (HARD RULE)--------
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:    #hard-rule (mandatory to satisfy)
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In              
      #           values:
      #           - mavenwebapp              # or nginx
      #       topologyKey: "kubernetes.io/hostname"
      #       namespaceSelector: {}

      tolerations:
      - key: node
        value: HatePods
        operator: Equal
        effect: NoSchedule
      

      containers:
        - name: mavenwebappcontainer
          image: dockerhandson/maven-web-application:1
          ports:
            - containerPort: 8080
          # resources:
          #   requests:
          #     cpu: 200m
          #     memory: 256Mi
          #   limits:
          #     cpu: 500m
          #     memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
